# Generated by Django 6.0.8 on 2026-08-18 12:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gazetteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255, unique=True)),
                (
                    "geom_wgs84",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "geom_local",
                    django.contrib.gis.db.models.fields.GeometryField(srid=32650),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GazetteerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=255)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_aliases",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="gazetteer.gazetteer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dataset__isnull", True)),
                        fields=("alias",),
                        name="unique_general_alias",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("dataset__isnull", False)),
                        fields=("dataset", "alias"),
                        name="unique_dataset_alias",
                    ),
                ],
            },
        ),
    ]
